# coding: utf-8

"""
    Fulfillment API

    Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.  # noqa: E501

    OpenAPI spec version: v1.19.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import ebayfulfillment
from ebayfulfillment.api.payment_dispute_api import PaymentDisputeApi  # noqa: E501
from ebayfulfillment.rest import ApiException


class TestPaymentDisputeApi(unittest.TestCase):
    """PaymentDisputeApi unit test stubs"""

    def setUp(self):
        self.api = PaymentDisputeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_accept_payment_dispute(self):
        """Test case for accept_payment_dispute

        Accept Payment Dispute  # noqa: E501
        """
        pass

    def test_add_evidence(self):
        """Test case for add_evidence

        Add an Evidence File  # noqa: E501
        """
        pass

    def test_contest_payment_dispute(self):
        """Test case for contest_payment_dispute

        Contest Payment Dispute  # noqa: E501
        """
        pass

    def test_fetch_evidence_content(self):
        """Test case for fetch_evidence_content

        Get Payment Dispute Evidence File  # noqa: E501
        """
        pass

    def test_get_activities(self):
        """Test case for get_activities

        Get Payment Dispute Activity  # noqa: E501
        """
        pass

    def test_get_payment_dispute(self):
        """Test case for get_payment_dispute

        Get Payment Dispute Details  # noqa: E501
        """
        pass

    def test_get_payment_dispute_summaries(self):
        """Test case for get_payment_dispute_summaries

        Search Payment Dispute by Filters  # noqa: E501
        """
        pass

    def test_update_evidence(self):
        """Test case for update_evidence

        Update evidence  # noqa: E501
        """
        pass

    def test_upload_evidence_file(self):
        """Test case for upload_evidence_file

        Upload an Evidence File  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
