# coding: utf-8

"""
    Fulfillment API

    Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.

    The version of the OpenAPI document: v1.20.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ebayfulfillment.models.buyer import Buyer

class TestBuyer(unittest.TestCase):
    """Buyer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Buyer:
        """Test Buyer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Buyer`
        """
        model = Buyer()
        if include_optional:
            return Buyer(
                buyer_registration_address = ebayfulfillment.models.extended_contact.ExtendedContact(
                    company_name = '', 
                    contact_address = ebayfulfillment.models.address.Address(
                        address_line1 = '', 
                        address_line2 = '', 
                        city = '', 
                        country_code = '', 
                        county = '', 
                        postal_code = '', 
                        state_or_province = '', ), 
                    email = '', 
                    full_name = '', 
                    primary_phone = ebayfulfillment.models.phone_number.PhoneNumber(
                        phone_number = '', ), ),
                tax_address = ebayfulfillment.models.tax_address.TaxAddress(
                    city = '', 
                    country_code = '', 
                    postal_code = '', 
                    state_or_province = '', ),
                tax_identifier = ebayfulfillment.models.tax_identifier.TaxIdentifier(
                    taxpayer_id = '', 
                    tax_identifier_type = '', 
                    issuing_country = '', ),
                username = ''
            )
        else:
            return Buyer(
        )
        """

    def testBuyer(self):
        """Test Buyer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
