# coding: utf-8

"""
    Analytics API

    The <b>Analytics API</b> retrieves call-limit data and the quotas that are set for the RESTful APIs and the legacy Trading API.  <br><br>Responses from calls made to <b>getRateLimits</b> and <b>getUerRateLimits</b> include a list of the applicable resources and the \"call limit\", or quota, that is set for each resource. In addition to quota information, the response also includes the number of remaining calls available before the limit is reached, the time remaining before the quota resets, and the length of the \"time window\" to which the quota applies.  <br><br>The <b>getRateLimits</b> and <b>getUserRateLimits</b> methods retrieve call-limit information for either an application or user, respectively, and each method must be called with an appropriate OAuth token. That is, <b>getRateLimites</b> requires an access token generated with a client credentials grant and <b>getUserRateLimites</b> requires an access token generated with an authorization code grant. For more information, see <a href=\"/api-docs/static/oauth-tokens.html\">OAuth tokens</a>.  <br><br>Users can analyze the response data to see whether or not a limit might be reached, and from that determine if any action needs to be taken (such as programmatically throttling their request rate). For more on call limits, see <a href=\"https://developer.ebay.com/support/app-check \" target=\"_blank\">Application Growth Check</a>.  # noqa: E501

    OpenAPI spec version: v1_beta.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from setuptools import setup, find_packages  # noqa: H301

NAME = "ebayanalytics"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="Analytics API",
    author_email="",
    url="",
    keywords=["Swagger", "Analytics API"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    The &lt;b&gt;Analytics API&lt;/b&gt; retrieves call-limit data and the quotas that are set for the RESTful APIs and the legacy Trading API.  &lt;br&gt;&lt;br&gt;Responses from calls made to &lt;b&gt;getRateLimits&lt;/b&gt; and &lt;b&gt;getUerRateLimits&lt;/b&gt; include a list of the applicable resources and the \&quot;call limit\&quot;, or quota, that is set for each resource. In addition to quota information, the response also includes the number of remaining calls available before the limit is reached, the time remaining before the quota resets, and the length of the \&quot;time window\&quot; to which the quota applies.  &lt;br&gt;&lt;br&gt;The &lt;b&gt;getRateLimits&lt;/b&gt; and &lt;b&gt;getUserRateLimits&lt;/b&gt; methods retrieve call-limit information for either an application or user, respectively, and each method must be called with an appropriate OAuth token. That is, &lt;b&gt;getRateLimites&lt;/b&gt; requires an access token generated with a client credentials grant and &lt;b&gt;getUserRateLimites&lt;/b&gt; requires an access token generated with an authorization code grant. For more information, see &lt;a href&#x3D;\&quot;/api-docs/static/oauth-tokens.html\&quot;&gt;OAuth tokens&lt;/a&gt;.  &lt;br&gt;&lt;br&gt;Users can analyze the response data to see whether or not a limit might be reached, and from that determine if any action needs to be taken (such as programmatically throttling their request rate). For more on call limits, see &lt;a href&#x3D;\&quot;https://developer.ebay.com/support/app-check \&quot; target&#x3D;\&quot;_blank\&quot;&gt;Application Growth Check&lt;/a&gt;.  # noqa: E501
    """
)
