# coding: utf-8

"""
    Account v1 API

    The <b>Account API</b> gives sellers the ability to configure their eBay seller accounts, including the seller's policies (eBay business policies and seller-defined custom policies), opt in and out of eBay seller programs, configure sales tax tables, and get account information.  <br><br>For details on the availability of the methods in this API, see <a href=\"/api-docs/sell/account/overview.html#requirements\">Account API requirements and restrictions</a>.

    The version of the OpenAPI document: v1.9.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ebayaccount.models.set_payment_policy_response import SetPaymentPolicyResponse

class TestSetPaymentPolicyResponse(unittest.TestCase):
    """SetPaymentPolicyResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SetPaymentPolicyResponse:
        """Test SetPaymentPolicyResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SetPaymentPolicyResponse`
        """
        model = SetPaymentPolicyResponse()
        if include_optional:
            return SetPaymentPolicyResponse(
                category_types = [
                    ebayaccount.models.category_type.CategoryType(
                        default = True, 
                        name = '', )
                    ],
                deposit = ebayaccount.models.deposit.Deposit(
                    amount = ebayaccount.models.amount.Amount(
                        currency = '', 
                        value = '', ), 
                    due_in = ebayaccount.models.time_duration.TimeDuration(
                        unit = '', 
                        value = 56, ), 
                    payment_methods = [
                        ebayaccount.models.payment_method.PaymentMethod(
                            brands = [
                                ''
                                ], 
                            payment_method_type = '', 
                            recipient_account_reference = ebayaccount.models.recipient_account_reference.RecipientAccountReference(
                                reference_id = '', 
                                reference_type = '', ), )
                        ], ),
                description = '',
                full_payment_due_in = ebayaccount.models.time_duration.TimeDuration(
                    unit = '', 
                    value = 56, ),
                immediate_pay = True,
                marketplace_id = '',
                name = '',
                payment_instructions = '',
                payment_methods = [
                    ebayaccount.models.payment_method.PaymentMethod(
                        brands = [
                            ''
                            ], 
                        payment_method_type = '', 
                        recipient_account_reference = ebayaccount.models.recipient_account_reference.RecipientAccountReference(
                            reference_id = '', 
                            reference_type = '', ), )
                    ],
                payment_policy_id = '',
                warnings = [
                    ebayaccount.models.error.Error(
                        category = '', 
                        domain = '', 
                        error_id = 56, 
                        input_ref_ids = [
                            ''
                            ], 
                        long_message = '', 
                        message = '', 
                        output_ref_ids = [
                            ''
                            ], 
                        parameters = [
                            ebayaccount.models.error_parameter.ErrorParameter(
                                name = '', 
                                value = '', )
                            ], 
                        subdomain = '', )
                    ]
            )
        else:
            return SetPaymentPolicyResponse(
        )
        """

    def testSetPaymentPolicyResponse(self):
        """Test SetPaymentPolicyResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
