# coding: utf-8

"""
    Metadata API

    The Metadata API has operations that retrieve configuration details pertaining to the different eBay marketplaces. In addition to marketplace information, the API also has operations that get information that helps sellers list items on eBay.

    The version of the OpenAPI document: v1.11.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ebaymetadata.models.property_names_response import PropertyNamesResponse

class TestPropertyNamesResponse(unittest.TestCase):
    """PropertyNamesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PropertyNamesResponse:
        """Test PropertyNamesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PropertyNamesResponse`
        """
        model = PropertyNamesResponse()
        if include_optional:
            return PropertyNamesResponse(
                category_id = '',
                properties = [
                    ebaymetadata.models.property_names_response_properties.PropertyNamesResponseProperties(
                        dataset = '', 
                        property_names = [
                            ebaymetadata.models.property_names_response_property_names.PropertyNamesResponsePropertyNames(
                                property_display_name = '', 
                                property_name = '', 
                                property_name_metadata = ebaymetadata.models.property_names_response_property_name_metadata.PropertyNamesResponsePropertyNameMetadata(
                                    display_sequence = 56, ), )
                            ], )
                    ]
            )
        else:
            return PropertyNamesResponse(
        )
        """

    def testPropertyNamesResponse(self):
        """Test PropertyNamesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
