# coding: utf-8

"""
    Metadata API

    The Metadata API has operations that retrieve configuration details pertaining to the different eBay marketplaces. In addition to marketplace information, the API also has operations that get information that helps sellers list items on eBay.  # noqa: E501

    OpenAPI spec version: v1.11.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import ebaymetadata
from ebaymetadata.models.sort_order_properties import SortOrderProperties  # noqa: E501
from ebaymetadata.rest import ApiException


class TestSortOrderProperties(unittest.TestCase):
    """SortOrderProperties unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSortOrderProperties(self):
        """Test SortOrderProperties"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ebaymetadata.models.sort_order_properties.SortOrderProperties()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
