# coding: utf-8

"""
    Metadata API

    The Metadata API has operations that retrieve configuration details pertaining to the different eBay marketplaces. In addition to marketplace information, the API also has operations that get information that helps sellers list items on eBay.

    The version of the OpenAPI document: v1.11.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ebaymetadata.models.regulatory_policy_response import RegulatoryPolicyResponse

class TestRegulatoryPolicyResponse(unittest.TestCase):
    """RegulatoryPolicyResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RegulatoryPolicyResponse:
        """Test RegulatoryPolicyResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RegulatoryPolicyResponse`
        """
        model = RegulatoryPolicyResponse()
        if include_optional:
            return RegulatoryPolicyResponse(
                regulatory_policies = [
                    ebaymetadata.models.regulatory_policy.RegulatoryPolicy(
                        category_id = '', 
                        category_tree_id = '', 
                        supported_attributes = [
                            ebaymetadata.models.regulatory_attribute.RegulatoryAttribute(
                                name = '', 
                                usage = '', )
                            ], )
                    ],
                warnings = [
                    ebaymetadata.models.error.Error(
                        category = '', 
                        domain = '', 
                        error_id = 56, 
                        input_ref_ids = [
                            ''
                            ], 
                        long_message = '', 
                        message = '', 
                        output_ref_ids = [
                            ''
                            ], 
                        parameters = [
                            ebaymetadata.models.error_parameter.ErrorParameter(
                                name = '', 
                                value = '', )
                            ], 
                        subdomain = '', )
                    ]
            )
        else:
            return RegulatoryPolicyResponse(
        )
        """

    def testRegulatoryPolicyResponse(self):
        """Test RegulatoryPolicyResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
