# coding: utf-8

"""
    Metadata API

    The Metadata API has operations that retrieve configuration details pertaining to the different eBay marketplaces. In addition to marketplace information, the API also has operations that get information that helps sellers list items on eBay.

    The version of the OpenAPI document: v1.11.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ebaymetadata.models.item_condition import ItemCondition

class TestItemCondition(unittest.TestCase):
    """ItemCondition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ItemCondition:
        """Test ItemCondition
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ItemCondition`
        """
        model = ItemCondition()
        if include_optional:
            return ItemCondition(
                condition_description = '',
                condition_descriptors = [
                    ebaymetadata.models.item_condition_descriptor.ItemConditionDescriptor(
                        condition_descriptor_constraint = ebaymetadata.models.item_condition_descriptor_constraint.ItemConditionDescriptorConstraint(
                            applicable_to_condition_descriptor_ids = [
                                ''
                                ], 
                            cardinality = '', 
                            default_condition_descriptor_value_id = '', 
                            max_length = 56, 
                            mode = '', 
                            usage = '', ), 
                        condition_descriptor_help_text = '', 
                        condition_descriptor_id = '', 
                        condition_descriptor_name = '', 
                        condition_descriptor_values = [
                            ebaymetadata.models.item_condition_descriptor_value.ItemConditionDescriptorValue(
                                condition_descriptor_value_additional_help_text = [
                                    ''
                                    ], 
                                condition_descriptor_value_constraints = [
                                    ebaymetadata.models.item_condition_descriptor_value_constraint.ItemConditionDescriptorValueConstraint(
                                        applicable_to_condition_descriptor_id = '', 
                                        applicable_to_condition_descriptor_value_ids = [
                                            ''
                                            ], )
                                    ], 
                                condition_descriptor_value_help_text = '', 
                                condition_descriptor_value_id = '', 
                                condition_descriptor_value_name = '', )
                            ], )
                    ],
                condition_help_text = '',
                condition_id = '',
                usage = ''
            )
        else:
            return ItemCondition(
        )
        """

    def testItemCondition(self):
        """Test ItemCondition"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
