# coding: utf-8

"""
    Metadata API

    The Metadata API has operations that retrieve configuration details pertaining to the different eBay marketplaces. In addition to marketplace information, the API also has operations that get information that helps sellers list items on eBay.  # noqa: E501

    OpenAPI spec version: v1.11.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import ebaymetadata
from ebaymetadata.api.compatibilities_api import CompatibilitiesApi  # noqa: E501
from ebaymetadata.rest import ApiException


class TestCompatibilitiesApi(unittest.TestCase):
    """CompatibilitiesApi unit test stubs"""

    def setUp(self):
        self.api = CompatibilitiesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_compatibilities_by_specification(self):
        """Test case for get_compatibilities_by_specification

        """
        pass

    def test_get_compatibility_property_names(self):
        """Test case for get_compatibility_property_names

        """
        pass

    def test_get_compatibility_property_values(self):
        """Test case for get_compatibility_property_values

        """
        pass

    def test_get_multi_compatibility_property_values(self):
        """Test case for get_multi_compatibility_property_values

        """
        pass

    def test_get_product_compatibilities(self):
        """Test case for get_product_compatibilities

        """
        pass


if __name__ == '__main__':
    unittest.main()
