# coding: utf-8

"""
    Metadata API

    The Metadata API has operations that retrieve configuration details pertaining to the different eBay marketplaces. In addition to marketplace information, the API also has operations that get information that helps sellers list items on eBay.

    The version of the OpenAPI document: v1.11.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ebaymetadata.models.site_visibility_policies_response import SiteVisibilityPoliciesResponse

class TestSiteVisibilityPoliciesResponse(unittest.TestCase):
    """SiteVisibilityPoliciesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SiteVisibilityPoliciesResponse:
        """Test SiteVisibilityPoliciesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SiteVisibilityPoliciesResponse`
        """
        model = SiteVisibilityPoliciesResponse()
        if include_optional:
            return SiteVisibilityPoliciesResponse(
                site_visibility_policies = [
                    ebaymetadata.models.site_visibility_policy.SiteVisibilityPolicy(
                        category_id = '', 
                        category_tree_id = '', 
                        cross_border_trade_australia_enabled = True, 
                        cross_border_trade_gb_enabled = True, 
                        cross_border_trade_north_america_enabled = True, )
                    ],
                warnings = [
                    ebaymetadata.models.error.Error(
                        category = '', 
                        domain = '', 
                        error_id = 56, 
                        input_ref_ids = [
                            ''
                            ], 
                        long_message = '', 
                        message = '', 
                        output_ref_ids = [
                            ''
                            ], 
                        parameters = [
                            ebaymetadata.models.error_parameter.ErrorParameter(
                                name = '', 
                                value = '', )
                            ], 
                        subdomain = '', )
                    ]
            )
        else:
            return SiteVisibilityPoliciesResponse(
        )
        """

    def testSiteVisibilityPoliciesResponse(self):
        """Test SiteVisibilityPoliciesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
