# coding: utf-8

"""
    Metadata API

    The Metadata API has operations that retrieve configuration details pertaining to the different eBay marketplaces. In addition to marketplace information, the API also has operations that get information that helps sellers list items on eBay.

    The version of the OpenAPI document: v1.11.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ebaymetadata.models.item_condition_policy_response import ItemConditionPolicyResponse

class TestItemConditionPolicyResponse(unittest.TestCase):
    """ItemConditionPolicyResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ItemConditionPolicyResponse:
        """Test ItemConditionPolicyResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ItemConditionPolicyResponse`
        """
        model = ItemConditionPolicyResponse()
        if include_optional:
            return ItemConditionPolicyResponse(
                item_condition_policies = [
                    ebaymetadata.models.item_condition_policy.ItemConditionPolicy(
                        category_id = '', 
                        category_tree_id = '', 
                        item_condition_required = True, 
                        item_conditions = [
                            ebaymetadata.models.item_condition.ItemCondition(
                                condition_description = '', 
                                condition_descriptors = [
                                    ebaymetadata.models.item_condition_descriptor.ItemConditionDescriptor(
                                        condition_descriptor_constraint = ebaymetadata.models.item_condition_descriptor_constraint.ItemConditionDescriptorConstraint(
                                            applicable_to_condition_descriptor_ids = [
                                                ''
                                                ], 
                                            cardinality = '', 
                                            default_condition_descriptor_value_id = '', 
                                            max_length = 56, 
                                            mode = '', 
                                            usage = '', ), 
                                        condition_descriptor_help_text = '', 
                                        condition_descriptor_id = '', 
                                        condition_descriptor_name = '', 
                                        condition_descriptor_values = [
                                            ebaymetadata.models.item_condition_descriptor_value.ItemConditionDescriptorValue(
                                                condition_descriptor_value_additional_help_text = [
                                                    ''
                                                    ], 
                                                condition_descriptor_value_constraints = [
                                                    ebaymetadata.models.item_condition_descriptor_value_constraint.ItemConditionDescriptorValueConstraint(
                                                        applicable_to_condition_descriptor_id = '', 
                                                        applicable_to_condition_descriptor_value_ids = [
                                                            ''
                                                            ], )
                                                    ], 
                                                condition_descriptor_value_help_text = '', 
                                                condition_descriptor_value_id = '', 
                                                condition_descriptor_value_name = '', )
                                            ], )
                                    ], 
                                condition_help_text = '', 
                                condition_id = '', 
                                usage = '', )
                            ], )
                    ],
                warnings = [
                    ebaymetadata.models.error.Error(
                        category = '', 
                        domain = '', 
                        error_id = 56, 
                        input_ref_ids = [
                            ''
                            ], 
                        long_message = '', 
                        message = '', 
                        output_ref_ids = [
                            ''
                            ], 
                        parameters = [
                            ebaymetadata.models.error_parameter.ErrorParameter(
                                name = '', 
                                value = '', )
                            ], 
                        subdomain = '', )
                    ]
            )
        else:
            return ItemConditionPolicyResponse(
        )
        """

    def testItemConditionPolicyResponse(self):
        """Test ItemConditionPolicyResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
