# coding: utf-8

"""
    Metadata API

    The Metadata API has operations that retrieve configuration details pertaining to the different eBay marketplaces. In addition to marketplace information, the API also has operations that get information that helps sellers list items on eBay.

    The version of the OpenAPI document: v1.11.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ebaymetadata.models.specification_response import SpecificationResponse

class TestSpecificationResponse(unittest.TestCase):
    """SpecificationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SpecificationResponse:
        """Test SpecificationResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SpecificationResponse`
        """
        model = SpecificationResponse()
        if include_optional:
            return SpecificationResponse(
                compatibility_details = [
                    ebaymetadata.models.compatibility.Compatibility(
                        compatibility_details = [
                            ebaymetadata.models.compatibility_details.CompatibilityDetails(
                                property_name = '', 
                                property_value = '', )
                            ], )
                    ],
                pagination = ebaymetadata.models.pagination.Pagination(
                    count = 56, 
                    limit = 56, 
                    offset = 56, 
                    total = 56, )
            )
        else:
            return SpecificationResponse(
        )
        """

    def testSpecificationResponse(self):
        """Test SpecificationResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
