# coding: utf-8

"""
    Metadata API

    The Metadata API has operations that retrieve configuration details pertaining to the different eBay marketplaces. In addition to marketplace information, the API also has operations that get information that helps sellers list items on eBay.

    The version of the OpenAPI document: v1.11.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ebaymetadata.api.compatibilities_api import CompatibilitiesApi


class TestCompatibilitiesApi(unittest.TestCase):
    """CompatibilitiesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CompatibilitiesApi()

    def tearDown(self) -> None:
        pass

    def test_get_compatibilities_by_specification(self) -> None:
        """Test case for get_compatibilities_by_specification

        """
        pass

    def test_get_compatibility_property_names(self) -> None:
        """Test case for get_compatibility_property_names

        """
        pass

    def test_get_compatibility_property_values(self) -> None:
        """Test case for get_compatibility_property_values

        """
        pass

    def test_get_multi_compatibility_property_values(self) -> None:
        """Test case for get_multi_compatibility_property_values

        """
        pass

    def test_get_product_compatibilities(self) -> None:
        """Test case for get_product_compatibilities

        """
        pass


if __name__ == '__main__':
    unittest.main()
