# coding: utf-8

# flake8: noqa

"""
    Negotiation API

    The <b>Negotiations API</b> gives sellers the ability to proactively send discount offers to buyers who have shown an \"interest\" in their listings.  <br><br>By sending buyers discount offers on listings where they have shown an interest, sellers can increase the velocity of their sales.  <br><br>There are various ways for a buyer to show <i>interest </i> in a listing. For example, if a buyer adds the listing to their <b>Watch</b> list, or if they add the listing to their shopping cart and later abandon the cart, they are deemed to have shown an interest in the listing.  <br><br>In the offers that sellers send, they can discount their listings by either a percentage off the listing price, or they can set a new discounted price that is lower than the original listing price.  <br><br>For details about how seller offers work, see <a href=\"/api-docs/sell/static/marketing/offers-to-buyers.html\" title=\"Selling Integration Guide\">Sending offers to buyers</a>.

    The version of the OpenAPI document: v1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "OfferApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "Amount",
    "CreateOffersRequest",
    "EligibleItem",
    "Error",
    "ErrorParameter",
    "Offer",
    "OfferedItem",
    "PagedEligibleItemCollection",
    "SendOfferToInterestedBuyersCollectionResponse",
    "TimeDuration",
    "User",
]

# import apis into sdk package
from ebaynegotiation.api.offer_api import OfferApi as OfferApi

# import ApiClient
from ebaynegotiation.api_response import ApiResponse as ApiResponse
from ebaynegotiation.api_client import ApiClient as ApiClient
from ebaynegotiation.configuration import Configuration as Configuration
from ebaynegotiation.exceptions import OpenApiException as OpenApiException
from ebaynegotiation.exceptions import ApiTypeError as ApiTypeError
from ebaynegotiation.exceptions import ApiValueError as ApiValueError
from ebaynegotiation.exceptions import ApiKeyError as ApiKeyError
from ebaynegotiation.exceptions import ApiAttributeError as ApiAttributeError
from ebaynegotiation.exceptions import ApiException as ApiException

# import models into sdk package
from ebaynegotiation.models.amount import Amount as Amount
from ebaynegotiation.models.create_offers_request import CreateOffersRequest as CreateOffersRequest
from ebaynegotiation.models.eligible_item import EligibleItem as EligibleItem
from ebaynegotiation.models.error import Error as Error
from ebaynegotiation.models.error_parameter import ErrorParameter as ErrorParameter
from ebaynegotiation.models.offer import Offer as Offer
from ebaynegotiation.models.offered_item import OfferedItem as OfferedItem
from ebaynegotiation.models.paged_eligible_item_collection import PagedEligibleItemCollection as PagedEligibleItemCollection
from ebaynegotiation.models.send_offer_to_interested_buyers_collection_response import SendOfferToInterestedBuyersCollectionResponse as SendOfferToInterestedBuyersCollectionResponse
from ebaynegotiation.models.time_duration import TimeDuration as TimeDuration
from ebaynegotiation.models.user import User as User

