# coding: utf-8

"""
    Media API

    The <b>Media API</b> lets sellers to create, upload, and retrieve files, including:<ul><li>videos</li><li>documents (for GPSR regulations)</li></ul>  # noqa: E501

    OpenAPI spec version: v1_beta.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import ebaymedia
from ebaymedia.api.document_api import DocumentApi  # noqa: E501
from ebaymedia.rest import ApiException


class TestDocumentApi(unittest.TestCase):
    """DocumentApi unit test stubs"""

    def setUp(self):
        self.api = DocumentApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_document(self):
        """Test case for create_document

        """
        pass

    def test_get_document(self):
        """Test case for get_document

        """
        pass

    def test_upload_document(self):
        """Test case for upload_document

        """
        pass


if __name__ == '__main__':
    unittest.main()
