# coding: utf-8

"""
    Media API

    The <strong>Media API</strong> lets sellers to create, upload, and retrieve files, including:<ul><li>images</li><li>videos</li><li>documents for Regulatory requirements</li><li>documents for post-order activities (such as returns)</li></ul>

    The version of the OpenAPI document: v1_beta.5.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ebaymedia.models.document_response import DocumentResponse

class TestDocumentResponse(unittest.TestCase):
    """DocumentResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DocumentResponse:
        """Test DocumentResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DocumentResponse`
        """
        model = DocumentResponse()
        if include_optional:
            return DocumentResponse(
                document_id = '',
                document_metadata = ebaymedia.models.document_metadata.DocumentMetadata(
                    file_name = '', 
                    file_size = '', 
                    file_type = '', ),
                document_status = 'SUBMITTED',
                document_type = 'CERTIFICATE_OF_ANALYSIS',
                languages = [
                    'ENGLISH'
                    ]
            )
        else:
            return DocumentResponse(
                document_id = '',
                document_status = 'SUBMITTED',
                document_type = 'CERTIFICATE_OF_ANALYSIS',
                languages = [
                    'ENGLISH'
                    ],
        )
        """

    def testDocumentResponse(self):
        """Test DocumentResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
