# coding: utf-8

"""
    Media API

    The <b>Media API</b> lets sellers to create, upload, and retrieve files, including:<ul><li>videos</li><li>documents (for GPSR regulations)</li></ul>  # noqa: E501

    OpenAPI spec version: v1_beta.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import ebaymedia
from ebaymedia.api.video_api import VideoApi  # noqa: E501
from ebaymedia.rest import ApiException


class TestVideoApi(unittest.TestCase):
    """VideoApi unit test stubs"""

    def setUp(self):
        self.api = VideoApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_video(self):
        """Test case for create_video

        """
        pass

    def test_get_video(self):
        """Test case for get_video

        """
        pass

    def test_upload_video(self):
        """Test case for upload_video

        """
        pass


if __name__ == '__main__':
    unittest.main()
