# coding: utf-8

"""
    Media API

    The <b>Media API</b> lets sellers to create, upload, and retrieve files, including:<ul><li>images</li><li>videos</li><li>documents (for GPSR regulations)</li></ul>

    The version of the OpenAPI document: v1_beta.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ebaymedia.models.create_image_from_url_request import CreateImageFromUrlRequest

class TestCreateImageFromUrlRequest(unittest.TestCase):
    """CreateImageFromUrlRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateImageFromUrlRequest:
        """Test CreateImageFromUrlRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateImageFromUrlRequest`
        """
        model = CreateImageFromUrlRequest()
        if include_optional:
            return CreateImageFromUrlRequest(
                image_url = ''
            )
        else:
            return CreateImageFromUrlRequest(
        )
        """

    def testCreateImageFromUrlRequest(self):
        """Test CreateImageFromUrlRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
