# coding: utf-8

"""
    Media API

    The <b>Media API</b> lets sellers to create, upload, and retrieve files, including:<ul><li>images</li><li>videos</li><li>documents (for GPSR regulations)</li></ul>

    The version of the OpenAPI document: v1_beta.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ebaymedia.models.moderation import Moderation

class TestModeration(unittest.TestCase):
    """Moderation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Moderation:
        """Test Moderation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Moderation`
        """
        model = Moderation()
        if include_optional:
            return Moderation(
                reject_reasons = [
                    ''
                    ]
            )
        else:
            return Moderation(
        )
        """

    def testModeration(self):
        """Test Moderation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
