# coding: utf-8

"""
    Media API

    The <strong>Media API</strong> lets sellers to create, upload, and retrieve files, including:<ul><li>images</li><li>videos</li><li>documents for Regulatory requirements</li><li>documents for post-order activities (such as returns)</li></ul>

    The version of the OpenAPI document: v1_beta.5.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ebaymedia.api.video_api import VideoApi


class TestVideoApi(unittest.TestCase):
    """VideoApi unit test stubs"""

    def setUp(self) -> None:
        self.api = VideoApi()

    def tearDown(self) -> None:
        pass

    def test_create_video(self) -> None:
        """Test case for create_video

        """
        pass

    def test_get_video(self) -> None:
        """Test case for get_video

        """
        pass

    def test_upload_video(self) -> None:
        """Test case for upload_video

        """
        pass


if __name__ == '__main__':
    unittest.main()
