# coding: utf-8

"""
    Media API

    The <strong>Media API</strong> lets sellers to create, upload, and retrieve files, including:<ul><li>images</li><li>videos</li><li>documents for Regulatory requirements</li><li>documents for post-order activities (such as returns)</li></ul>

    The version of the OpenAPI document: v1_beta.5.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ebaymedia.api.post_order_api import PostOrderApi


class TestPostOrderApi(unittest.TestCase):
    """PostOrderApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PostOrderApi()

    def tearDown(self) -> None:
        pass

    def test_download_post_order_document(self) -> None:
        """Test case for download_post_order_document

        """
        pass

    def test_remove_post_order_document(self) -> None:
        """Test case for remove_post_order_document

        """
        pass

    def test_upload_post_order_document(self) -> None:
        """Test case for upload_post_order_document

        """
        pass


if __name__ == '__main__':
    unittest.main()
