# coding: utf-8

"""
    Inventory API

    The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.

    The version of the OpenAPI document: 1.18.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from ebayinventory.models.availability_distribution import AvailabilityDistribution
from ebayinventory.models.format_allocation import FormatAllocation
from typing import Optional, Set
from typing_extensions import Self

class ShipToLocationAvailabilityWithAll(BaseModel):
    """
    This type is used to specify the total 'ship-to-home' quantity of the inventory items that will be available for purchase through one or more published offers.
    """ # noqa: E501
    allocation_by_format: Optional[FormatAllocation] = Field(default=None, alias="allocationByFormat")
    availability_distributions: Optional[List[AvailabilityDistribution]] = Field(default=None, description="This container is used to set the available quantity of the inventory item at one or more warehouse locations.<br><br>This container will be returned if the available quantity is set for one or more inventory locations.", alias="availabilityDistributions")
    quantity: Optional[StrictInt] = Field(default=None, description="<div class=\"msgbox_important\"><p class=\"msgbox_importantInDiv\" data-mc-autonum=\"&lt;b&gt;&lt;span style=&quot;color: #dd1e31;&quot; class=&quot;mcFormatColor&quot;&gt;Important! &lt;/span&gt;&lt;/b&gt;\"><span class=\"autonumber\"><span><b><span style=\"color: #dd1e31;\" class=\"mcFormatColor\">Important!</span></b></span></span> Publish offer note: Although this field is not required before an offer can be published to create an active listing, out of stock listings will result if this field is omitted or set to <code>0</code>.</p></div><br>This field is used to set the total 'ship-to-home' quantity of the inventory item that will be available for purchase through one or more published offers. This field is not immediately required, but 'ship-to-home' quantity must be set before an offer of the inventory item can be published.<br><br>If an existing inventory item is being updated, and the 'ship-to-home' quantity already exists for the inventory item record, this field should be included again, even if the value is not changing, or the available quantity data will be lost.")
    __properties: ClassVar[List[str]] = ["allocationByFormat", "availabilityDistributions", "quantity"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ShipToLocationAvailabilityWithAll from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of allocation_by_format
        if self.allocation_by_format:
            _dict['allocationByFormat'] = self.allocation_by_format.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in availability_distributions (list)
        _items = []
        if self.availability_distributions:
            for _item_availability_distributions in self.availability_distributions:
                if _item_availability_distributions:
                    _items.append(_item_availability_distributions.to_dict())
            _dict['availabilityDistributions'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ShipToLocationAvailabilityWithAll from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "allocationByFormat": FormatAllocation.from_dict(obj["allocationByFormat"]) if obj.get("allocationByFormat") is not None else None,
            "availabilityDistributions": [AvailabilityDistribution.from_dict(_item) for _item in obj["availabilityDistributions"]] if obj.get("availabilityDistributions") is not None else None,
            "quantity": obj.get("quantity")
        })
        return _obj


