# coding: utf-8

"""
    Inventory API

    The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.

    The version of the OpenAPI document: 1.18.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ebayinventory.models.bulk_publish_response import BulkPublishResponse

class TestBulkPublishResponse(unittest.TestCase):
    """BulkPublishResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BulkPublishResponse:
        """Test BulkPublishResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BulkPublishResponse`
        """
        model = BulkPublishResponse()
        if include_optional:
            return BulkPublishResponse(
                responses = [
                    ebayinventory.models.offer_response_with_listing_id.OfferResponseWithListingId(
                        errors = [
                            ebayinventory.models.error.Error(
                                category = '', 
                                domain = '', 
                                error_id = 56, 
                                input_ref_ids = [
                                    ''
                                    ], 
                                long_message = '', 
                                message = '', 
                                output_ref_ids = [
                                    ''
                                    ], 
                                parameters = [
                                    ebayinventory.models.error_parameter.ErrorParameter(
                                        name = '', 
                                        value = '', )
                                    ], 
                                subdomain = '', )
                            ], 
                        listing_id = '', 
                        offer_id = '', 
                        status_code = 56, 
                        warnings = [
                            ebayinventory.models.error.Error(
                                category = '', 
                                domain = '', 
                                error_id = 56, 
                                long_message = '', 
                                message = '', 
                                subdomain = '', )
                            ], )
                    ]
            )
        else:
            return BulkPublishResponse(
        )
        """

    def testBulkPublishResponse(self):
        """Test BulkPublishResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
