# coding: utf-8

"""
    Inventory API

    The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.

    The version of the OpenAPI document: 1.18.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ebayinventory.models.product_family_properties import ProductFamilyProperties

class TestProductFamilyProperties(unittest.TestCase):
    """ProductFamilyProperties unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductFamilyProperties:
        """Test ProductFamilyProperties
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductFamilyProperties`
        """
        model = ProductFamilyProperties()
        if include_optional:
            return ProductFamilyProperties(
                engine = '',
                make = '',
                model = '',
                trim = '',
                year = ''
            )
        else:
            return ProductFamilyProperties(
        )
        """

    def testProductFamilyProperties(self):
        """Test ProductFamilyProperties"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
