# coding: utf-8

"""
    Inventory API

    The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.

    The version of the OpenAPI document: 1.18.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ebayinventory.api.inventory_item_api import InventoryItemApi


class TestInventoryItemApi(unittest.TestCase):
    """InventoryItemApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InventoryItemApi()

    def tearDown(self) -> None:
        pass

    def test_bulk_create_or_replace_inventory_item(self) -> None:
        """Test case for bulk_create_or_replace_inventory_item

        """
        pass

    def test_bulk_get_inventory_item(self) -> None:
        """Test case for bulk_get_inventory_item

        """
        pass

    def test_bulk_update_price_quantity(self) -> None:
        """Test case for bulk_update_price_quantity

        """
        pass

    def test_create_or_replace_inventory_item(self) -> None:
        """Test case for create_or_replace_inventory_item

        """
        pass

    def test_delete_inventory_item(self) -> None:
        """Test case for delete_inventory_item

        """
        pass

    def test_get_inventory_item(self) -> None:
        """Test case for get_inventory_item

        """
        pass

    def test_get_inventory_items(self) -> None:
        """Test case for get_inventory_items

        """
        pass


if __name__ == '__main__':
    unittest.main()
