# coding: utf-8

"""
    Inventory API

    The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.

    The version of the OpenAPI document: 1.18.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ebayinventory.models.varies_by import VariesBy

class TestVariesBy(unittest.TestCase):
    """VariesBy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VariesBy:
        """Test VariesBy
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VariesBy`
        """
        model = VariesBy()
        if include_optional:
            return VariesBy(
                aspects_image_varies_by = [
                    ''
                    ],
                specifications = [
                    ebayinventory.models.specification.Specification(
                        name = '', 
                        values = [
                            ''
                            ], )
                    ]
            )
        else:
            return VariesBy(
        )
        """

    def testVariesBy(self):
        """Test VariesBy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
