# coding: utf-8

"""
    Inventory API

    The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.

    The version of the OpenAPI document: 1.18.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ebayinventory.api.listing_api import ListingApi


class TestListingApi(unittest.TestCase):
    """ListingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ListingApi()

    def tearDown(self) -> None:
        pass

    def test_bulk_migrate_listing(self) -> None:
        """Test case for bulk_migrate_listing

        """
        pass

    def test_create_or_replace_sku_location_mapping(self) -> None:
        """Test case for create_or_replace_sku_location_mapping

        """
        pass

    def test_delete_sku_location_mapping(self) -> None:
        """Test case for delete_sku_location_mapping

        """
        pass

    def test_get_sku_location_mapping(self) -> None:
        """Test case for get_sku_location_mapping

        """
        pass


if __name__ == '__main__':
    unittest.main()
