# coding: utf-8

"""
    Inventory API

    The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.

    The version of the OpenAPI document: 1.18.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ebayinventory.models.regulatory import Regulatory

class TestRegulatory(unittest.TestCase):
    """Regulatory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Regulatory:
        """Test Regulatory
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Regulatory`
        """
        model = Regulatory()
        if include_optional:
            return Regulatory(
                documents = [
                    ebayinventory.models.document.Document(
                        document_id = '', )
                    ],
                energy_efficiency_label = ebayinventory.models.energy_efficiency_label.EnergyEfficiencyLabel(
                    image_description = '', 
                    image_url = '', 
                    product_information_sheet = '', ),
                hazmat = ebayinventory.models.hazmat.Hazmat(
                    component = '', 
                    pictograms = [
                        ''
                        ], 
                    signal_word = '', 
                    statements = [
                        ''
                        ], ),
                manufacturer = ebayinventory.models.manufacturer.Manufacturer(
                    address_line1 = '', 
                    address_line2 = '', 
                    city = '', 
                    company_name = '', 
                    contact_url = '', 
                    country = '', 
                    email = '', 
                    phone = '', 
                    postal_code = '', 
                    state_or_province = '', ),
                product_safety = ebayinventory.models.product_safety.ProductSafety(
                    component = '', 
                    pictograms = [
                        ''
                        ], 
                    statements = [
                        ''
                        ], ),
                repair_score = 1.337,
                responsible_persons = [
                    ebayinventory.models.responsible_person.ResponsiblePerson(
                        address_line1 = '', 
                        address_line2 = '', 
                        city = '', 
                        company_name = '', 
                        contact_url = '', 
                        country = '', 
                        email = '', 
                        phone = '', 
                        postal_code = '', 
                        state_or_province = '', 
                        types = [
                            ''
                            ], )
                    ]
            )
        else:
            return Regulatory(
        )
        """

    def testRegulatory(self):
        """Test Regulatory"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
