# coding: utf-8

"""
    Inventory API

    The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.

    The version of the OpenAPI document: 1.18.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ebayinventory.models.product_safety import ProductSafety

class TestProductSafety(unittest.TestCase):
    """ProductSafety unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductSafety:
        """Test ProductSafety
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductSafety`
        """
        model = ProductSafety()
        if include_optional:
            return ProductSafety(
                component = '',
                pictograms = [
                    ''
                    ],
                statements = [
                    ''
                    ]
            )
        else:
            return ProductSafety(
        )
        """

    def testProductSafety(self):
        """Test ProductSafety"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
