# coding: utf-8

"""
    Media API

    The <strong>Media API</strong> lets sellers to create, upload, and retrieve files, including:<ul><li>images</li><li>videos</li><li>documents for Regulatory requirements</li><li>documents for post-order activities (such as returns)</li></ul>

    The version of the OpenAPI document: v1_beta.5.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ProtocolEnum(str, Enum):
    """
    An enumerated type that indicates whether the video streaming protocol is DASH (Dynamic Adaptive Streaming over HTTP) or HLS (HTTP Live Streaming).<br /><br />DASH is also known as MPEG-DASH. It is an internationally accepted protocol for streaming video. It splits a larger media file into much smaller segments.<br /><br />HLS is a format developed by Apple. Rather than deliver a video file all at once, HLS splits it into much smaller segments. Since HLS was developed by Apple, it is the only method of video streaming currently supported on iOS (iPad and iPhone) and is supported natively within its Mac Safari browser. | - **DASH**: The video streaming protocol is DASH (Dynamic Adaptive Streaming over HTTP). - **HLS**: The video streaming protocol is HLS (HTTP Live Streaming).
    """

    """
    allowed enum values
    """
    DASH = 'DASH'
    HLS = 'HLS'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ProtocolEnum from a JSON string"""
        return cls(json.loads(json_str))


