# coding: utf-8

"""
    Metadata API

    The Metadata API has operations that retrieve configuration details pertaining to the different eBay marketplaces. In addition to marketplace information, the API also has operations that get information that helps sellers list items on eBay.

    The version of the OpenAPI document: v1.11.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ClassifiedAdPolicy(BaseModel):
    """
    This type provides fields that contains applicable Classified Ad policy metadata for the leaf categories returned for the marketplace.
    """ # noqa: E501
    ad_format_enabled: Optional[StrictStr] = Field(default=None, description="This enumerated value indicates the type or status of available Classified Ad formats for this category. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/metadata/types/sel:AdFormatEnabledEnum'>eBay API documentation</a>", alias="adFormatEnabled")
    category_id: Optional[StrictStr] = Field(default=None, description="The unique identifier of the eBay leaf category for which metadata is being returned.", alias="categoryId")
    category_tree_id: Optional[StrictStr] = Field(default=None, description="The unique identifier of the category tree.", alias="categoryTreeId")
    classified_ad_auto_accept_enabled: Optional[StrictBool] = Field(default=None, description="Indicates whether the category supports the Best Offer Automatic Accept feature for Classified Ad listings.", alias="classifiedAdAutoAcceptEnabled")
    classified_ad_auto_decline_enabled: Optional[StrictBool] = Field(default=None, description="Indicates whether the category supports the Best Offer Automatic Reject feature for Classified Ad listings.", alias="classifiedAdAutoDeclineEnabled")
    classified_ad_best_offer_enabled: Optional[StrictStr] = Field(default=None, description="This enumerated value indicates if Best Offer is enabled, disabled, or required for Classified Ad listings in this category. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/metadata/types/sel:ClassifiedAdBestOfferEnabledEnum'>eBay API documentation</a>", alias="classifiedAdBestOfferEnabled")
    classified_ad_company_name_enabled: Optional[StrictBool] = Field(default=None, description="Indicates whether this category supports including a company name in the seller's contact information. This element is for <b>For Sale By Owner</b> listings. ", alias="classifiedAdCompanyNameEnabled")
    classified_ad_contact_by_address_enabled: Optional[StrictBool] = Field(default=None, description="Indicates whether this category supports including an address in the seller's contact information. This element is for <b>For Sale By Owner</b> listings. ", alias="classifiedAdContactByAddressEnabled")
    classified_ad_contact_by_email_enabled: Optional[StrictBool] = Field(default=None, description="Indicates whether most categories support including an email address in the seller's contact information.", alias="classifiedAdContactByEmailEnabled")
    classified_ad_contact_by_phone_enabled: Optional[StrictBool] = Field(default=None, description="Indicates whether most categories support including a phone number in the seller's contact information.", alias="classifiedAdContactByPhoneEnabled")
    classified_ad_counter_offer_enabled: Optional[StrictBool] = Field(default=None, description="Indicates whether counter offers are allowed on Best offers for the category.", alias="classifiedAdCounterOfferEnabled")
    classified_ad_payment_method_enabled: Optional[StrictStr] = Field(default=None, description="This enumerated value indicates support for the payment method being displayed to the user for the category. Even if enabled, checkout may or may not be enabled. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/metadata/types/sel:ClassifiedAdPaymentMethodEnabledEnum'>eBay API documentation</a>", alias="classifiedAdPaymentMethodEnabled")
    classified_ad_phone_count: Optional[StrictInt] = Field(default=None, description="Indicates how many contact phone numbers can be specified in contact information for the category. This element is for <b>For Sale By Owner</b> listings.", alias="classifiedAdPhoneCount")
    classified_ad_shipping_method_enabled: Optional[StrictBool] = Field(default=None, description="Indicates if shipping methods can be specified and displayed in the <b>View Item</b> page for the category.", alias="classifiedAdShippingMethodEnabled")
    classified_ad_street_count: Optional[StrictInt] = Field(default=None, description="Indicates how many street addresses can be specified in contact information for the category. This element is for <b>For Sale By Owner</b> listings.", alias="classifiedAdStreetCount")
    seller_contact_details_enabled: Optional[StrictBool] = Field(default=None, description="Indicates whether this category supports seller-level contact information for Classified Ad listings.", alias="sellerContactDetailsEnabled")
    __properties: ClassVar[List[str]] = ["adFormatEnabled", "categoryId", "categoryTreeId", "classifiedAdAutoAcceptEnabled", "classifiedAdAutoDeclineEnabled", "classifiedAdBestOfferEnabled", "classifiedAdCompanyNameEnabled", "classifiedAdContactByAddressEnabled", "classifiedAdContactByEmailEnabled", "classifiedAdContactByPhoneEnabled", "classifiedAdCounterOfferEnabled", "classifiedAdPaymentMethodEnabled", "classifiedAdPhoneCount", "classifiedAdShippingMethodEnabled", "classifiedAdStreetCount", "sellerContactDetailsEnabled"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ClassifiedAdPolicy from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ClassifiedAdPolicy from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "adFormatEnabled": obj.get("adFormatEnabled"),
            "categoryId": obj.get("categoryId"),
            "categoryTreeId": obj.get("categoryTreeId"),
            "classifiedAdAutoAcceptEnabled": obj.get("classifiedAdAutoAcceptEnabled"),
            "classifiedAdAutoDeclineEnabled": obj.get("classifiedAdAutoDeclineEnabled"),
            "classifiedAdBestOfferEnabled": obj.get("classifiedAdBestOfferEnabled"),
            "classifiedAdCompanyNameEnabled": obj.get("classifiedAdCompanyNameEnabled"),
            "classifiedAdContactByAddressEnabled": obj.get("classifiedAdContactByAddressEnabled"),
            "classifiedAdContactByEmailEnabled": obj.get("classifiedAdContactByEmailEnabled"),
            "classifiedAdContactByPhoneEnabled": obj.get("classifiedAdContactByPhoneEnabled"),
            "classifiedAdCounterOfferEnabled": obj.get("classifiedAdCounterOfferEnabled"),
            "classifiedAdPaymentMethodEnabled": obj.get("classifiedAdPaymentMethodEnabled"),
            "classifiedAdPhoneCount": obj.get("classifiedAdPhoneCount"),
            "classifiedAdShippingMethodEnabled": obj.get("classifiedAdShippingMethodEnabled"),
            "classifiedAdStreetCount": obj.get("classifiedAdStreetCount"),
            "sellerContactDetailsEnabled": obj.get("sellerContactDetailsEnabled")
        })
        return _obj


