# coding: utf-8

"""
    Metadata API

    The Metadata API has operations that retrieve configuration details pertaining to the different eBay marketplaces. In addition to marketplace information, the API also has operations that get information that helps sellers list items on eBay.

    The version of the OpenAPI document: v1.11.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from ebaymetadata.models.item_condition_descriptor_value_constraint import ItemConditionDescriptorValueConstraint
from typing import Optional, Set
from typing_extensions import Self

class ItemConditionDescriptorValue(BaseModel):
    """
    This type displays the possible values for the corresponding condition descriptor, along with help text and constraint information.
    """ # noqa: E501
    condition_descriptor_value_additional_help_text: Optional[List[StrictStr]] = Field(default=None, description="Additional information about the the condition of the item that is not included in the <b>conditionDescriptorValueHelpText</b> field.", alias="conditionDescriptorValueAdditionalHelpText")
    condition_descriptor_value_constraints: Optional[List[ItemConditionDescriptorValueConstraint]] = Field(default=None, description="The constraints on a condition descriptor value, such as which descriptor value IDs and Descriptor ID it is associated with.", alias="conditionDescriptorValueConstraints")
    condition_descriptor_value_help_text: Optional[StrictStr] = Field(default=None, description="A detailed description of the condition descriptor value. ", alias="conditionDescriptorValueHelpText")
    condition_descriptor_value_id: Optional[StrictStr] = Field(default=None, description="The unique identification number of a condition descriptor value associated with the <b>conditionDescriptorValueName</b>.", alias="conditionDescriptorValueId")
    condition_descriptor_value_name: Optional[StrictStr] = Field(default=None, description="The human-readable label for the condition descriptor value associated with the <b>conditionDescriptorValueID</b>.", alias="conditionDescriptorValueName")
    __properties: ClassVar[List[str]] = ["conditionDescriptorValueAdditionalHelpText", "conditionDescriptorValueConstraints", "conditionDescriptorValueHelpText", "conditionDescriptorValueId", "conditionDescriptorValueName"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ItemConditionDescriptorValue from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in condition_descriptor_value_constraints (list)
        _items = []
        if self.condition_descriptor_value_constraints:
            for _item_condition_descriptor_value_constraints in self.condition_descriptor_value_constraints:
                if _item_condition_descriptor_value_constraints:
                    _items.append(_item_condition_descriptor_value_constraints.to_dict())
            _dict['conditionDescriptorValueConstraints'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ItemConditionDescriptorValue from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "conditionDescriptorValueAdditionalHelpText": obj.get("conditionDescriptorValueAdditionalHelpText"),
            "conditionDescriptorValueConstraints": [ItemConditionDescriptorValueConstraint.from_dict(_item) for _item in obj["conditionDescriptorValueConstraints"]] if obj.get("conditionDescriptorValueConstraints") is not None else None,
            "conditionDescriptorValueHelpText": obj.get("conditionDescriptorValueHelpText"),
            "conditionDescriptorValueId": obj.get("conditionDescriptorValueId"),
            "conditionDescriptorValueName": obj.get("conditionDescriptorValueName")
        })
        return _obj


