from typing import TYPE_CHECKING, Any, Dict, List, Type, TypeVar, Union

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.error import Error
    from ..models.negotiated_price_policy import NegotiatedPricePolicy


T = TypeVar("T", bound="NegotiatedPricePolicyResponse")


@_attrs_define
class NegotiatedPricePolicyResponse:
    """
    Attributes:
        negotiated_price_policies (Union[Unset, List['NegotiatedPricePolicy']]): A list of category IDs and the policies
            related to negotiated-price items for each of the listed categories.
        warnings (Union[Unset, List['Error']]): A list of the warnings that were generated as a result of the request.
            This field is not returned if no warnings were generated by the request.
    """

    negotiated_price_policies: Union[Unset, List["NegotiatedPricePolicy"]] = UNSET
    warnings: Union[Unset, List["Error"]] = UNSET
    additional_properties: Dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        negotiated_price_policies: Union[Unset, List[Dict[str, Any]]] = UNSET
        if not isinstance(self.negotiated_price_policies, Unset):
            negotiated_price_policies = []
            for negotiated_price_policies_item_data in self.negotiated_price_policies:
                negotiated_price_policies_item = negotiated_price_policies_item_data.to_dict()
                negotiated_price_policies.append(negotiated_price_policies_item)

        warnings: Union[Unset, List[Dict[str, Any]]] = UNSET
        if not isinstance(self.warnings, Unset):
            warnings = []
            for warnings_item_data in self.warnings:
                warnings_item = warnings_item_data.to_dict()
                warnings.append(warnings_item)

        field_dict: Dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if negotiated_price_policies is not UNSET:
            field_dict["negotiatedPricePolicies"] = negotiated_price_policies
        if warnings is not UNSET:
            field_dict["warnings"] = warnings

        return field_dict

    @classmethod
    def from_dict(cls: Type[T], src_dict: Dict[str, Any]) -> T:
        from ..models.error import Error
        from ..models.negotiated_price_policy import NegotiatedPricePolicy

        d = src_dict.copy()
        negotiated_price_policies = []
        _negotiated_price_policies = d.pop("negotiatedPricePolicies", UNSET)
        for negotiated_price_policies_item_data in _negotiated_price_policies or []:
            negotiated_price_policies_item = NegotiatedPricePolicy.from_dict(negotiated_price_policies_item_data)

            negotiated_price_policies.append(negotiated_price_policies_item)

        warnings = []
        _warnings = d.pop("warnings", UNSET)
        for warnings_item_data in _warnings or []:
            warnings_item = Error.from_dict(warnings_item_data)

            warnings.append(warnings_item)

        negotiated_price_policy_response = cls(
            negotiated_price_policies=negotiated_price_policies,
            warnings=warnings,
        )

        negotiated_price_policy_response.additional_properties = d
        return negotiated_price_policy_response

    @property
    def additional_keys(self) -> List[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
