from typing import TYPE_CHECKING, Any, Dict, List, Type, TypeVar, Union

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.error import Error
    from ..models.regulatory_policy import RegulatoryPolicy


T = TypeVar("T", bound="RegulatoryPolicyResponse")


@_attrs_define
class RegulatoryPolicyResponse:
    """A type that defines the response fields for the <b>getRegulatoryPolicies</b> method.

    Attributes:
        regulatory_policies (Union[Unset, List['RegulatoryPolicy']]): A list of eBay policies that define whether or not
            you must include required regulatory information for leaf categories on the given marketplace.
        warnings (Union[Unset, List['Error']]): A list of the warnings that were generated as a result of the request.
            This field is not returned if no warnings were generated by the request.
    """

    regulatory_policies: Union[Unset, List["RegulatoryPolicy"]] = UNSET
    warnings: Union[Unset, List["Error"]] = UNSET
    additional_properties: Dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        regulatory_policies: Union[Unset, List[Dict[str, Any]]] = UNSET
        if not isinstance(self.regulatory_policies, Unset):
            regulatory_policies = []
            for regulatory_policies_item_data in self.regulatory_policies:
                regulatory_policies_item = regulatory_policies_item_data.to_dict()
                regulatory_policies.append(regulatory_policies_item)

        warnings: Union[Unset, List[Dict[str, Any]]] = UNSET
        if not isinstance(self.warnings, Unset):
            warnings = []
            for warnings_item_data in self.warnings:
                warnings_item = warnings_item_data.to_dict()
                warnings.append(warnings_item)

        field_dict: Dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if regulatory_policies is not UNSET:
            field_dict["regulatoryPolicies"] = regulatory_policies
        if warnings is not UNSET:
            field_dict["warnings"] = warnings

        return field_dict

    @classmethod
    def from_dict(cls: Type[T], src_dict: Dict[str, Any]) -> T:
        from ..models.error import Error
        from ..models.regulatory_policy import RegulatoryPolicy

        d = src_dict.copy()
        regulatory_policies = []
        _regulatory_policies = d.pop("regulatoryPolicies", UNSET)
        for regulatory_policies_item_data in _regulatory_policies or []:
            regulatory_policies_item = RegulatoryPolicy.from_dict(regulatory_policies_item_data)

            regulatory_policies.append(regulatory_policies_item)

        warnings = []
        _warnings = d.pop("warnings", UNSET)
        for warnings_item_data in _warnings or []:
            warnings_item = Error.from_dict(warnings_item_data)

            warnings.append(warnings_item)

        regulatory_policy_response = cls(
            regulatory_policies=regulatory_policies,
            warnings=warnings,
        )

        regulatory_policy_response.additional_properties = d
        return regulatory_policy_response

    @property
    def additional_keys(self) -> List[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
