# coding: utf-8

"""
     Seller Service Metrics API 

    The Analytics API provides data and information about a seller and their eBay business. The resources and methods in this API let sellers review information on their listing performance, metrics on their customer service performance, and details on their eBay seller performance rating. The three resources in the Analytics API provide the following data and information: Customer Service Metric &ndash; Returns data on a seller's customer service performance as compared to other seller's in the same peer group. Traffic Report &ndash; Returns data that shows how buyers are engaging with a seller's listings. Seller Standards Profile &ndash; Returns data pertaining to a seller's performance rating. Sellers can use the data and information returned by the various Analytics API methods to determine where they can make improvements to increase sales and how they might improve their seller status as viewed by eBay buyers. For details on using this API, see Analyzing seller performance.

    OpenAPI spec version: 1.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class Metadata(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, metadata_header=None, metadata_records=None):
        """
        Metadata - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'metadata_header': 'MetadataHeader',
            'metadata_records': 'list[MetadataRecord]'
        }

        self.attribute_map = {
            'metadata_header': 'metadataHeader',
            'metadata_records': 'metadataRecords'
        }

        self._metadata_header = metadata_header
        self._metadata_records = metadata_records

    @property
    def metadata_header(self):
        """
        Gets the metadata_header of this Metadata.


        :return: The metadata_header of this Metadata.
        :rtype: MetadataHeader
        """
        return self._metadata_header

    @metadata_header.setter
    def metadata_header(self, metadata_header):
        """
        Sets the metadata_header of this Metadata.


        :param metadata_header: The metadata_header of this Metadata.
        :type: MetadataHeader
        """

        self._metadata_header = metadata_header

    @property
    def metadata_records(self):
        """
        Gets the metadata_records of this Metadata.
        A list of the individual report records.

        :return: The metadata_records of this Metadata.
        :rtype: list[MetadataRecord]
        """
        return self._metadata_records

    @metadata_records.setter
    def metadata_records(self, metadata_records):
        """
        Sets the metadata_records of this Metadata.
        A list of the individual report records.

        :param metadata_records: The metadata_records of this Metadata.
        :type: list[MetadataRecord]
        """

        self._metadata_records = metadata_records

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
