# coding: utf-8

"""
     Seller Service Metrics API 

    The Analytics API provides data and information about a seller and their eBay business. The resources and methods in this API let sellers review information on their listing performance, metrics on their customer service performance, and details on their eBay seller performance rating. The three resources in the Analytics API provide the following data and information: Customer Service Metric &ndash; Returns data on a seller's customer service performance as compared to other seller's in the same peer group. Traffic Report &ndash; Returns data that shows how buyers are engaging with a seller's listings. Seller Standards Profile &ndash; Returns data pertaining to a seller's performance rating. Sellers can use the data and information returned by the various Analytics API methods to determine where they can make improvements to increase sales and how they might improve their seller status as viewed by eBay buyers. For details on using this API, see Analyzing seller performance.

    OpenAPI spec version: 1.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

# import models into sdk package
from .models.benchmark_metadata import BenchmarkMetadata
from .models.cycle import Cycle
from .models.definition import Definition
from .models.dimension import Dimension
from .models.dimension_metric import DimensionMetric
from .models.distribution import Distribution
from .models.error import Error
from .models.error_parameter import ErrorParameter
from .models.evaluation_cycle import EvaluationCycle
from .models.find_seller_standards_profiles_response import FindSellerStandardsProfilesResponse
from .models.get_customer_service_metric_response import GetCustomerServiceMetricResponse
from .models.header import Header
from .models.metadata import Metadata
from .models.metadata_header import MetadataHeader
from .models.metadata_record import MetadataRecord
from .models.metric import Metric
from .models.metric_benchmark import MetricBenchmark
from .models.metric_distribution import MetricDistribution
from .models.record import Record
from .models.report import Report
from .models.standards_profile import StandardsProfile
from .models.value import Value

# import apis into sdk package
from .apis.customerservicemetric_api import CustomerservicemetricApi
from .apis.sellerstandardsprofile_api import SellerstandardsprofileApi
from .apis.trafficreport_api import TrafficreportApi

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration

configuration = Configuration()
