# coding: utf-8

"""
    Finances API

    This API is used to retrieve seller payouts and monetary transaction details related to those payouts.

    The version of the OpenAPI document: v1.17.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ebayfinance.models.payout import Payout

class TestPayout(unittest.TestCase):
    """Payout unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Payout:
        """Test Payout
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Payout`
        """
        model = Payout()
        if include_optional:
            return Payout(
                amount = ebayfinance.models.amount.Amount(
                    converted_from_currency = '', 
                    converted_from_value = '', 
                    converted_to_currency = '', 
                    converted_to_value = '', 
                    currency = '', 
                    exchange_rate = '', 
                    value = '', ),
                bank_reference = '',
                last_attempted_payout_date = '',
                payout_date = '',
                payout_id = '',
                payout_instrument = ebayfinance.models.payout_instrument.PayoutInstrument(
                    account_last_four_digits = '', 
                    instrument_type = '', 
                    nickname = '', 
                    payout_percentage = '', ),
                payout_memo = '',
                payout_reference = '',
                payout_status = '',
                payout_status_description = '',
                total_amount = ebayfinance.models.amount.Amount(
                    converted_from_currency = '', 
                    converted_from_value = '', 
                    converted_to_currency = '', 
                    converted_to_value = '', 
                    currency = '', 
                    exchange_rate = '', 
                    value = '', ),
                total_fee = ebayfinance.models.amount.Amount(
                    converted_from_currency = '', 
                    converted_from_value = '', 
                    converted_to_currency = '', 
                    converted_to_value = '', 
                    currency = '', 
                    exchange_rate = '', 
                    value = '', ),
                total_fee_details = [
                    ebayfinance.models.fee.Fee(
                        amount = ebayfinance.models.amount.Amount(
                            converted_from_currency = '', 
                            converted_from_value = '', 
                            converted_to_currency = '', 
                            converted_to_value = '', 
                            currency = '', 
                            exchange_rate = '', 
                            value = '', ), 
                        fee_jurisdiction = ebayfinance.models.fee_jurisdiction.FeeJurisdiction(
                            region_name = '', 
                            region_type = '', ), 
                        fee_memo = '', 
                        fee_type = '', )
                    ],
                transaction_count = 56
            )
        else:
            return Payout(
        )
        """

    def testPayout(self):
        """Test Payout"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
