# coding: utf-8

"""
    eBay Finances API

    This API is used to retrieve seller payouts and monetary transaction details related to those payouts.  # noqa: E501

    OpenAPI spec version: 1.7.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import ebayfinance
from ebayfinance.models.transactions import Transactions  # noqa: E501
from ebayfinance.rest import ApiException


class TestTransactions(unittest.TestCase):
    """Transactions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactions(self):
        """Test Transactions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ebayfinance.models.transactions.Transactions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
